CREATE DATABASE DeliverySystem;
USE DeliverySystem;

CREATE TABLE VENDOR (VEN_ID INT AUTO_INCREMENT NOT NULL KEY,
VEN_NAME VARCHAR(50) NOT NULL,
VEN_PHONE_NUMBER VARCHAR(15) NOT NULL,
VEN_LOCATION VARCHAR(250) NOT NULL, VEN_RATING DECIMAL(4,2));

CREATE TABLE CUSTOMER (CUST_ID INT AUTO_INCREMENT NOT NULL KEY,
CUST_NAME CHAR(100) NOT NULL,
CUST_PHONE_NUMBER VARCHAR(15) NOT NULL, 
CUST_ORDER VARCHAR(50), 
CUST_LOCATION VARCHAR(250));

CREATE TABLE COURIER (CRR_ID INT AUTO_INCREMENT NOT NULL KEY,
CRR_LOCATION CHAR(100) NOT NULL, CRR_VEHICLE VARCHAR(20), 
CRR_DISTANCE DECIMAL(8,2),
CRR_PHONE_NUMBER VARCHAR(15) NOT NULL, 
CRR_NAME VARCHAR(50) NOT NULL, 
CRR_RATING DECIMAL(4,2) NOT NULL);

CREATE TABLE PAYMENT (PAY_ID INT AUTO_INCREMENT NOT NULL,
VEN_ID INT NOT NULL, 
CUST_ID INT NOT NULL,
PAY_METHOD ENUM('Cash', 'Credit', 'Debit', 'E-Wallet') NOT NULL,
PAY_AMOUNT DECIMAL(8,2) NOT NULL, 
PAY_TIP DECIMAL(8,2),
PRIMARY KEY(PAY_ID),
FOREIGN KEY(VEN_ID) REFERENCES VENDOR(VEN_ID),
FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID));

ALTER TABLE PAYMENT
ADD UNIQUE (PAY_TIP);

CREATE TABLE COMISSION (COM_ID INT AUTO_INCREMENT NOT NULL KEY,
CRR_ID INT NOT NULL,  
PAY_TIP DECIMAL(8,2), 
COM_AMOUNT DECIMAL(8,2) NOT NULL,
FOREIGN KEY (CRR_ID) REFERENCES COURIER(CRR_ID),
FOREIGN KEY(PAY_TIP) REFERENCES PAYMENT(PAY_TIP));

CREATE TABLE PRODUCT(
	PRD_ID INT AUTO_INCREMENT NOT NULL KEY,
    VEN_ID INT NOT NULL,
    PRD_NAME VARCHAR(50) NOT NULL,
    PRD_PRICE INT(5) NOT NULL,
    PRD_IMAGE BLOB, 
    PRD_AVAILABILITY BOOL NOT NULL,
    PRD_QUANTITY INT(5) NOT NULL,
    PRD_RATING DECIMAL(4,2), 
  FOREIGN KEY (VEN_ID) REFERENCES VENDOR(VEN_ID)  );
    
    

CREATE TABLE DELIVERY(
	DEL_ID INT NOT NULL KEY,
    CRR_ID INT NOT NULL,
    VEN_NAME VARCHAR(50) NOT NULL,
    VEN_ID INT NOT NULL,
    CUST_ID INT NOT NULL,
    PRD_NAME VARCHAR(50) NOT NULL,
    PRD_ID INT NOT NULL, 
    VEN_LOCATION VARCHAR(250) NOT NULL,
    CUST_LOCATION VARCHAR(250) NOT NULL,
    CRR_LOCATION CHAR(100) NOT NULL,
    FOREIGN KEY(CRR_ID) REFERENCES COURIER(CRR_ID),
    FOREIGN KEY(VEN_ID) REFERENCES VENDOR(VEN_ID),
    FOREIGN KEY(VEN_NAME) REFERENCES VENDOR(VEN_NAME),
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY(PRD_ID) REFERENCES  PRODUCT(PRD_ID),
    FOREIGN KEY(PRD_NAME) REFERENCES PRODUCT(PRD_NAME)
    );
    SELECT * FROM PRODUCT;