DROP DATABASE IF EXISTS DeliverySystem;
CREATE DATABASE DeliverySystem;
USE DeliverySystem;

-- ==========================================
-- 1. CORE ENTITY TABLES
-- ==========================================

-- VENDOR: Stores restaurant/shop details.
CREATE TABLE VENDOR (
    VEN_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VEN_NAME VARCHAR(100) NOT NULL,
    VEN_PHONE_NUMBER VARCHAR(15) NOT NULL,
    VEN_LOCATION VARCHAR(250) NOT NULL
);

-- CUSTOMER: Stores end-user profile data.
CREATE TABLE CUSTOMER (
    CUST_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CUST_NAME VARCHAR(100) NOT NULL,
    CUST_PHONE_NUMBER VARCHAR(15) NOT NULL, 
    CUST_LOCATION VARCHAR(250) NOT NULL
);

-- COURIER: Stores driver details and vehicle info.
CREATE TABLE COURIER (
    CRR_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CRR_NAME VARCHAR(50) NOT NULL, 
    CRR_PHONE_NUMBER VARCHAR(15) NOT NULL, 
    CRR_LOCATION VARCHAR(100) NOT NULL, 
    CRR_VEHICLE VARCHAR(50), 
    CRR_is_AVAILABLE BOOLEAN DEFAULT TRUE
);

-- PRODUCT: Stores items for sale. 
-- Linked to VENDOR via VEN_ID.
CREATE TABLE PRODUCT(
    PRD_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VEN_ID INT NOT NULL,
    PRD_NAME VARCHAR(100) NOT NULL,
    PRD_PRICE DECIMAL(10,2) NOT NULL, 
    PRD_AVAILABILITY BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (VEN_ID) REFERENCES VENDOR(VEN_ID) ON DELETE CASCADE
);

-- ==========================================
-- 2. TRANSACTION TABLE
-- ==========================================

-- DELIVERY: The central table merging Order, Payment, and Commission.
CREATE TABLE DELIVERY(
    DEL_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    
    -- Relationships
    CUST_ID INT NOT NULL,
    CRR_ID INT NOT NULL,
    PRD_ID INT NOT NULL, 
    
    -- Logistics Data
    DEL_STATUS ENUM('Pending', 'In-Transit', 'Delivered', 'Cancelled') DEFAULT 'Pending',
    DEL_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Financial Data (Merged from Payment/Commission tables)
    PAY_METHOD ENUM('Cash', 'Credit', 'Debit', 'E-Wallet'),
    PAY_AMOUNT DECIMAL(10,2) NOT NULL,    
    PAY_TIP DECIMAL(10,2) DEFAULT 0.00,   
    PAY_COMMISSION DECIMAL(10,2) NOT NULL, 

    -- Constraints
    FOREIGN KEY(CRR_ID) REFERENCES COURIER(CRR_ID),
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY(PRD_ID) REFERENCES PRODUCT(PRD_ID)
);
    
   